### ISSUE TITLE
content updates

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/cancer-microbiome-intervention-tutorial#3]
General content work:
- [x] add text to existing content
- [x] add days relative to FMT column (or something along those lines) 
- [x] search text for "TODO"; address or create issues for each (#42)
- [ ] identify missing citations, links to the library, etc and add

Sections that are not yet started:
- [x] all sections upstream of filtering - waiting to hear back on whether there is pre-SRA data accessible that can be used here
- [ ] _alpha diversity_ section: LME 
- ~differential abundance testing: pre/post FMT (note that this will be tricky b/c time series samples are not independent; consider visualizing aldex2 differentials with qurro~
- [ ] "q2FMT ideas" notebook (i.e., add analyses that will integrate FMT timepoint data, possibly drawing from [autism-fmt code](https://github.com/caporaso-lab/autism-fmt1/tree/18-month-followup))

**Comment by cherman2** [comment]
@gregcaporaso, is content on this still in progress? Please re-open if so.
