### ISSUE TITLE
Issue on page /040-appendices/convert-and-import-artifacts.html

### ISSUE THREAD

**Issue by bandy134** [qiime2/cancer-microbiome-intervention-tutorial#60]
i think the raw data has been removed. I just want to see what exactly "Artifact.import_data" does. Are there anyone could just help about it? thanks.

**Comment by lizgehret** [comment]
Hi @bandy134, are you referring to the dropbox links on [this page](https://docs.qiime2.org/jupyterbooks/cancer-microbiome-intervention-tutorial/040-appendices/convert-and-import-artifacts.html)?

**Comment by lizgehret** [comment]
Hey @bandy134, I'm going to go ahead and close this since we haven't heard back. Please feel free to follow up if you have more details!
